@startuml "main"
hide circle
scale 1920*1080
package main {
    class GamePanel {
        - tempScreen : BufferedImage
        - g2 : Graphics2D
        + fullScreenOn : boolean
        + currentMap : int
        - originalTileSize : int
        - scale : int
        + tileSize : int
        + maxScreenCol : int
        + maxScreenRow : int
        + maxWorldCol : int
        + maxWorldRow : int
        + maxMap : int
        + worldWidth : int
        + worldHeight : int
        + screenWidth : int
        + screenHeight : int
        + screenWidth2 : int
        + screenHeight2 : int
        + FPS : int
        + titleState : int
        + playState : int
        + pauseState : int
        + dialogueState : int
        + characterState : int
        + optionState : int
        + youLostState : int
        + guideState : int
        + menuOptionState : int
        + mapState : int
        + cutScene : int
        + bossBattleOn : boolean
        + tileM : TileManager
        + KeyH : KeyHandle
        + music : Sound
        + se : Sound
        + colDect : CollisionDetector
        + aSetter : AssetSetter
        + ui : UI
        + eHandler : EvenHandler
        + config : Config
        + map : Map
        + pFinder : PathFinder
        - eManager : EnvironmentManager
        + saveLoad : SaveLoad
        + csManager : CutSceneManager
        + gameThread : Thread
        + player : Player
        + obj : Entity[][]
        + npc : Entity[][]
        + monster : Entity[][]
        + mine : Entity[][]
        + projectileList : ArrayList<Entity>
        - entityList : ArrayList<Entity>
        + gameState : int
        + currentArea : int
        - screenWidth2 : int
        - screenHeight2 : int
        + bossBattleOn : boolean
        
        + GamePanel()
        + setupGame() : void
        + setFullScreen() : void
        + startGameThread() : void
        + run() : void
        + update() : void
        + drawToTempScreen() : void
        + addEntitiesToList(Entity[]) : void
        + drawToScreen() : void
        + playeMusic(int) : void
        + stopMusic() : void
        + playSE(int) : void
        + resetGame(boolean) : void
        + removeTempEntity() : void
    }
    class Main {
        + static window: JFrame
        + static main(args: String[]): void
    }
}
package entities {
    class Entity
    class Player
}
package managers {
    class AssetSetter
    class CollisionDetector
    class Config
    class CutSceneManager
    class EnvironmentManager
    class EvenHandler
    class KeyHandle
    class Sound
    class UI
}
package map {
    class Map
    class TileManager
}
package mics {
    class PathFinder
    class SaveLoad
}

GamePanel --> Entity
GamePanel --> Player
GamePanel --> AssetSetter
GamePanel --> CollisionDetector
GamePanel --> Config
GamePanel --> CutSceneManager
GamePanel --> EnvironmentManager
GamePanel --> EvenHandler
GamePanel --> KeyHandle
GamePanel --> Sound
GamePanel --> UI
GamePanel --> Map
GamePanel --> TileManager
GamePanel --> PathFinder
GamePanel --> SaveLoad
GamePanel --|> JPanel
GamePanel ..|> Runnable
@enduml 


